- name: Start a server
  hosts: all
  tasks:

    - name: start
      ansible.builtin.shell:
        cmd: sudo systemctl start httpd
        
    - name: check
      ansible.builtin.shell:
        cmd: sudo systemctl status httpd
      register: result

    - name: debug
      ansible.builtin.debug:
        var: result
