---
- name: Listen for webhook 5000
  hosts: all
  sources:
  - ansible.eda.webhook:
      host: 0.0.0.0
      port: 5000
  rules:
  - name: Message ID1 received, action ID1 executed
    condition: event.payload.message == "1"
    action:
      run_job_template:
        name: AAP Notification to Teams
        organization: Default
        job_args:
          extra_vars:
            code: "{{ event.payload.message }}"
            message: "{{ event.payload.message }}"
